### PR TITLE
Add Fabric Loader 1.14~1.21(All is latest version)

### PR DESCRIPTION
**Pull request by naruko-hstk**
Wait to test.
Add Fabric Loader Support(From 1.14 to 1.21)
[WARNING] Before merge should test it.

### CODE REVIEW

**Comment by YuMao233** [comment]
Could you please run a test on them and tell me the results?

**Comment by naruko-hstk** [comment]
> Could you please run a test on them and tell me the results?

When I go home.
Now at my lab.

**Comment by huangsijun17** [comment]
Starting from Java 8, -server is used by default. This option is deprecated.

**Comment by naruko-hstk** [comment]
> Starting from Java 8, -server is used by default. This option is deprecated.

It use installer.
Not a server file.

**Pull request merged**
